site_name: Tubester RESTful API
nav:
    - Home: index.md
    - Endpoints:
      - '/admin':
        - '/data': 'endpoints/admin/data.md'
        - '/register': 'endpoints/admin/register.md'
      - '/user':
        - '/confirm': 'endpoints/user/confirm.md'
        - '/data': 'endpoints/user/data.md'
        - '/delete': 'endpoints/user/delete.md'
        - '/login': 'endpoints/user/login.md'
        - '/register': 'endpoints/user/register.md'
        - '/renew': 'endpoints/user/renew.md'
    - Data:
      - 'json web token': 'data/jwt.md'
      - 'UserInterface': 'data/user_interface.md'
theme: readthedocs